// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchSelectFiles():Promise<Array<string>>;

export function SetConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Upload(arg1:string,arg2:string):Promise<Array<string>>;
