// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchSelectFiles() {
  return window['go']['main']['App']['BatchSelectFiles']();
}

export function GetDomain() {
  return window['go']['main']['App']['GetDomain']();
}

export function Upload(arg1, arg2) {
  return window['go']['main']['App']['Upload'](arg1, arg2);
}
