// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchSelectFiles():Promise<Array<string>>;

export function GetDomain():Promise<string>;

export function Upload(arg1:string,arg2:string):Promise<Array<string>>;
