// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {multipart} from '../models';

export function Upload(arg1:string,arg2:Array<multipart.FileHeader>):Promise<Array<string>>;
